# Generated by Django 3.1 on 2021-03-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_interesttags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
