# Generated by Django 3.1 on 2021-03-05 04:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210304_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default=ckeditor.fields.RichTextField(blank=True, null=True), max_length=200),
        ),
    ]
