# Generated by Django 3.1 on 2021-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210305_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
