# Generated by Django 3.1 on 2021-03-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210305_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
