# Generated by Django 3.1 on 2021-03-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='header_image',
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
