# Generated by Django 3.1 on 2021-03-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210305_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
