# Generated by Django 3.1 on 2021-03-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
